### ISSUE TITLE
XOR

### ISSUE THREAD

**Issue by mvojacek** [jaywor1/aps#21]
U tech matematickych operatoru mi docela chybi XOR. Jsou i nejake dalsi, ale ty se v praxi nepouzivaji. XOR jo.

**Comment by jaywor1** [comment]
Přidán XOR viz. https://github.com/jaywor1/aps/pull/25

Má to nějaký symbol v predikátové logice? Zatím jsem tu buňku vynechal. @mvojacek

**Comment by mvojacek** [comment]
Ve výrokové logice by XOR byl inekvivalence (preskrtnuta ekvivalence). Jiný symbol pro to asi nemají, nepotřebují.
----------------------------------------

Nov 15, 2023 01:06:16 jaywor1 ***@***.***>:

**Comment by jaywor1** [comment]
https://github.com/jaywor1/aps/pull/25
