### ISSUE TITLE
Matouci NOR

### ISSUE THREAD

**Issue by mvojacek** [jaywor1/aps#22]
> [NOR](https://github.com/jaywor1/aps/blob/main/kapitoly/hradla.md#nor)
> 
> Hradlo NOR má opačný vstup hradla OR
> 
> Pokud neplatí A nebo B, tak pošli na výstup hodnotu 1

Tenhle popis mi prijde vic matouci nez prinosny.. Lepsi by bylo neco jako:

> Má výstup jedna pouze v případě, že A ani B nejsou 1.

**Comment by jaywor1** [comment]
:+1: 

https://github.com/jaywor1/aps/pull/24
