### ISSUE TITLE
[BUG] Dvojkový doplňek

### ISSUE THREAD

**Issue by mvojacek** [jaywor1/aps#55]
**URL odkaz na kapitoly**
https://jaywor1.github.io/aps/alu-scitacka.html#dvojkov%C3%BD-dopln%C4%9Bk-twos-complement

**Popsání chyby a její řešení**
Říct jenom, že dvojkový doplňěk má jako první bit znaménko, nestačí. Taková definice odvozuje spíš přímý kód. U dvojkového doplňku to sice je taky pravda (a je to důležité zmínit), ale odvození dvojkového doplňku probíhá trochu jinak:

Když máme n-bitové čísla, pracujeme v tělese $Z_{2^n}^+$ (tj. modulo $2^n$). V tomto tělese bychom chtěli postavit takový kód, který nám umožní právě odčítat pomocí sčítání, tj. pro každé kladné $b^+$ chceme aby existovalo nějaké $b^-$ takové, aby $a-b^+ = a+(-b^+) = a+b^-$. Pro toto $b^-$ tímpádem platí $b^+ + b^- = 0$ $(mod 2^n)$. Jde tedy o nalezení aditivní inverze v $Z_{2^n}^+$, takže $b^- = 2^n - b^+ = (2^n - 1) - b^+ + 1$. Číslo $2^n - 1$ je řetězec samých jedniček, a odečtením od takové hodnoty nikdy nenastane žádný přenos, a odečítaná hodnota se touto operací jednoduše zneguje. Dostáváme tedy pravidlo pro výpočet opačného čísla v tomto kódu: $b^- = \overline{b^+} + 1$. Tato vypočtená hodnota je samozřejmě nějaký bitový řetězec, jinak normálně platné číslo. V doplňkovém kódu považujeme b^- pro každé b^+ za záporné číslo. Všechny záporné čísla v tomto kódu (doplňkovém kódu) mají na nejvyšším bitu hodnotu 1, tento bit tedy můžeme zároveň považovat za znaménko. Zhruba polovina čísel je teď záporná (kvuli nule ne přesná polovina), takže maximální hodnota (ale teď jak do kladných i záporných čísel) je poloviční, než u stejně velkých čísel bez znaménka.

Já to vysvětluju na hodinách, a třeťáci k tomu ted mají potřebnej matematickej základ od Milana na KBB kryptografii, takže jako studijní text to takhle asi stačí. Můžeš to rewordnout, jak chceš. Bylo by fajn tam hodit kromě tabulky i takovej ten koláč, na něm se to dobře ilustruje, něco jako tohle: ![](https://docplayer.cz/docs-images/46/9446800/images/page_17.jpg)

**Comment by jaywor1** [comment]
https://github.com/jaywor1/aps/pull/58
