### ISSUE TITLE
[BUG] Full adder carry

### ISSUE THREAD

**Issue by mvojacek** [jaywor1/aps#56]
**URL odkaz na kapitoly**
https://jaywor1.github.io/aps/alu-scitacka.html#full-adder

**Popsání chyby a její řešení**
U full adderu navíc poznamenat, že pří sčítání 3 bitů je maximální hodnota 3, garantovaně se tedy vejde do 2 bitů. Správně se totiž mají carry outy z obou half adderů **sečíst**. Nicméně z toho, že výsledek se vejde do 2 bitů, a z pozorování, že pro libovolnou kombinaci vstupů nastane carry nejvýše na jednom z half adderů, můžeme pro sečtení těchto carry použít zjednodušené zapojení (OR gate), jelikož součet nikdy nemůže pretéci, a zároveň by neměl kam.

**Comment by jaywor1** [comment]
https://github.com/jaywor1/aps/pull/57
