### ISSUE TITLE
Typos a pravopis

### ISSUE THREAD

**Issue by aestheticdisaster** [jaywor1/aps#72]
### Typos a pravopis 

**Pro porozumění skript asi ani není třeba nějakého perfektního pravopisu a kde jakého překlepu si jde lehce nevšimnout, ale i tak je tady detailní výpis všech chyb, které jsem byla schopna najít.**

https://jaywor1.github.io/aps/multiplexory-dekodery.html

- Část Demultiplexor – “zhlediska” by mělo být zvlášť, jelikož se jedná o předložku, tedy “z hlediska”.

https://jaywor1.github.io/aps/alu-uvod.html

- Zavádějící písmeno “s” v části Výstupy ALU ve větě “…přidat operace s komparátoru...”. Pokud je tato věta míněna býti ve druhém pádě, je třeba napsat “z komparátoru”

https://jaywor1.github.io/aps/alu-scitacka.html

- Zde by měla být čárka hned v úvodu kapitoly ve větě “Začneme jednoduše, a to jedno bitovou verzí.”. Spojka a zde totiž není ve slučovacím poměru. 
- Typo ve slově “Pravdivostní”, kde je přebytečné písmeno – “pravdivnostní”, část Half-adder
- Typo hned vzápětí, kde je napsáno “karnughovy mapy”. Správně však “karnaughovy mapy”. Ve stejné větě je taktéž přebytečná čárka ve větě, před slovem “můžeme” by čárka být něměla. 
- Podruhé typo ve slově “Pravdivostní”, kde je přebytečné písmeno – “pravdivnostní”, část Full-adder
- Chybějící čárky ve větě “Jediné, co tedy uděláme, je, že…”
- Chyba v i/y ve větě “COUT half-adderů by se měli sčítat…” Zde by mělo být přepsáno na “měly”.
- Chybějící čárka v části Odčítačka ve větě “1 znamená - a 0 znamená + s tím, že…”

https://jaywor1.github.io/aps/sekvencni-obvody.html

- Zde by měla být čárka hned v úvodu kapitoly ve větě “Pomocí těchto cyklů nabírají zajímavé vlastnosti, a to paměti”. Spojka a zde totiž není ve slučovacím poměru. 
- Potřetí typo ve slově “pravdivnostní”, viz tentýž problém výše.
- Přebytečná čárka ve slově “okamžiku” v části Latch vs Flip flop, kde je “okamžíku”

https://jaywor1.github.io/aps/asynchronni-obvody.html

- Počtvrté typo “pravdivnostní”

https://jaywor1.github.io/aps/synchronni-obvody.html

- Po páté typo “pravdivnostní”
- V části D Flip flop je věta “D flip flop jde vytvořit spustu způsoby.” Zde je samozřejmě chybějící písmeno ve slově “spoustu”.
- Hned o větu dál je opakovaný problém s “a to”, kde by před spojkou a měla být čárka. 

https://jaywor1.github.io/aps/cpu-uvod.html

- Chybějící čárka ve slově “skládá” ve větě “CPU se typicky skláda”
- Přebytečná čárka ve slově “vysíláná” v části typů sběrnic “datová/data – pro výsíláná”

https://jaywor1.github.io/aps/cpu-design.html

- Typo ve slově “vlastností” v části Instrukce “… by mělo mít několik vlastnostní”
- Přebytečná čárka ve slově “interních” v části Vyžadované instrukce – Paměťové (kromě intérních…)

https://jaywor1.github.io/aps/cpu-build.html

- Chybějící čárka v souvětí v části Program counter. Věta by měla vypadat následovně: “Program counter je komponenta CPU, která vám říká, na jakém řádku programu…”

https://jaywor1.github.io/aps/cpu-programming.html

- Typo ve větě “Dobré podotknout, že jako typ…”. Ve slově podoktnout jsou prohozená písmena.

**Comment by jaywor1** [comment]
> Počtvrté typo “pravdivnostní”

Už jsem to radši vyřešil sedem :DD

https://github.com/jaywor1/aps/commit/49b2052a6b65dff78c989d2cace9a85f1bf604b5

**Comment by jaywor1** [comment]
> Typo ve slově “vlastností” v části Instrukce “… by mělo mít několik vlastnostní”

Ta varianta, která tam je by měla být správně viz. https://cs.wiktionary.org/wiki/vlastnost

**Comment by jaywor1** [comment]
Jinak pro příště nemusíš psát v časti x y, stačí kliknout na nadpis na webu a ono ti to přidá kotvu viz. Tohle je o prefernci, pokud by ses chtěla vypisovat, tak můžeš :D

>   Chybějící čárka v souvětí v části Program counter. Věta by měla vypadat následovně: “Program counter je komponenta CPU, která vám říká, na jakém řádku programu…”

https://jaywor1.github.io/aps/cpu-build.html#program-counter-pc

**Comment by jaywor1** [comment]
https://github.com/jaywor1/aps/pull/73

**Comment by aestheticdisaster** [comment]
> Ta varianta, která tam je by měla být správně viz. https://cs.wiktionary.org/wiki/vlastnost

To asi úplně nechápu, jak myslíš, jakože to původní slovo má být správně? To mi moc nedává smysl. Anebo jenom něco nechápu :D

> Jinak pro příště nemusíš psát v časti x y, stačí kliknout na nadpis na webu a ono ti to přidá kotvu viz. Tohle je o prefernci, pokud by ses chtěla vypisovat, tak můžeš :D

Jo, o kotvení na nadpisy samozřejmě vím, asi mi to jen kdovíproč přišlo v ten moment rychlejší to vypsat xd


Jinak ještě tady jsem si úplně na konci všimla překlepu ve slově toggle, ale mimo to je to snad prozatím všechno
https://jaywor1.github.io/aps/cpu-design.html#vy%C5%BEadovan%C3%A9-instrukce

**Comment by jaywor1** [comment]
ad vlastnost - asi jsem to commitnul or smth

ostatní chyby vyřešeny zavírám

https://github.com/jaywor1/aps/pull/76
