### ISSUE TITLE
Přidat přípravu na test z teorie

### ISSUE THREAD

**Issue by jaywor1** [jaywor1/aps#9]
Stejné příklady jako v testu jenom jiné zadání

**Comment by jaywor1** [comment]
Příklady 1-4 přidány, zbývá dodělat příklad 5

**Comment by mvojacek** [comment]
Pod pravidla booleovske algebry napat:

# Zjednodusovani vyrazu
...Pomoci pravidel zjednodusujeme vyrazy...
Link -> priklad z testu NEBO dalsi priklad

**Comment by jaywor1** [comment]
Link na příklad přidán

Mohl bys mi zkontrolovat prosím ten pátý příklad, který jsem tam přidal (normálně na `dev` branch) @mvojacek

**Comment by mvojacek** [comment]
Ten příklad vychází 1, je to patrné od chvíle, kdy je v toplevel součtu B + !B, což je tautologie.
Když zjednodušuješ příklad, chceš vždy udělat tu nejjednodušší úpravu, která má největší efekt. Např. hned na začátku můžeš využít asociativity a komutativity, a rozpustit závorky. Pak demorgan, B+!B, příklad je hotový, vychází 1.
Bylo by vhodné používat ty high level pravidla jako absorbce, abs. negace, jsou lehce identifikovatelne v tom příkladě (opakuje se pismenko mimo a uvnitř závorky s opačným znamenkem) a dělají paseku.
Navrhnout dobrý příklad není jednoduché nemůžeš dávat moc osamocených pismenek do toplevel součtu, abys vybalancoval počet jedniček ve výstupu. Můžu kdyztak nějaký poskytnout.
U toho zjednodušení by se mi líbilo nejak zvyraznit na dalším řádku provedenou upravu, jestli můžeš tak barvou, jinak treba bold. A na konec řádku nebo mezi ně napsat, jaké pravidla jsi použil, případně jak ta uprava konkretne tady vypadá (absorbce: A+A(B xor C) = A). Má to být studijní materiál, měl by popisovat co se tam vlastně děje.

U toho 3. prikladu, vyraz z zapojeni, mas stale staré * jako násobení.

U příkladu kde vytváříš zapojení, by bylo vhodné pod to zapojení poznamenat, že:
Hradla OR na pravé straně můžou být v libovolném pořadí nebo nahrazeny 3-vstupovým OR, jelikož sčítání je asociativní a komutativní.
U tabulky pak: Vytváření tabulky si ulehčíme spočítáním sloupců pro námi zvolené podvýrazy, jejich hodnoty použijeme v dalších výpočtech, abychom se vyhnuli chybám při počítání komplikovaných výrazu z hlavy. Pokud víme na první pohled hodnoty některých řádků výsledku, můžeme je vyplnit hned do výsledku a v pomocných sloupcích je přeskočit. Důležitý je pouze sloupec s výsledkem a sloupce ABC, zbytek jsou mezivýpočty.
tj. vysvětlit, jak to vlastne udělat, případně tipy a triky.
----------------------------------------

Nov 15, 2023 00:47:04 jaywor1 ***@***.***>:

**Comment by jaywor1** [comment]
> Ten příklad vychází 1, je to patrné od chvíle, kdy je v toplevel součtu B + !B, což je tautologie.

Už to vidím, výrazy nikdy nebyla moje silná stránka :D

> Navrhnout dobrý příklad není jednoduché nemůžeš dávat moc osamocených pismenek do toplevel součtu, abys vybalancoval počet jedniček ve výstupu. Můžu kdyztak nějaký poskytnout.

To by se hodilo

> U toho zjednodušení by se mi líbilo nejak zvyraznit na dalším řádku provedenou upravu, jestli můžeš tak barvou, jinak treba bold. 

V markdownu mně přijde nejlepší ten bold...

> U toho 3. prikladu, vyraz z zapojeni, mas stale staré * jako násobení.

Fixed

TODO:

> - [ ] U příkladu kde vytváříš zapojení, by bylo vhodné pod to zapojení poznamenat, že:
Hradla OR na pravé straně můžou být v libovolném pořadí nebo nahrazeny 3-vstupovým OR, jelikož sčítání je asociativní a komutativní.

> - [ ] U tabulky pak: Vytváření tabulky si ulehčíme spočítáním sloupců pro námi zvolené podvýrazy, jejich hodnoty použijeme v dalších výpočtech, abychom se vyhnuli chybám při počítání komplikovaných výrazu z hlavy. Pokud víme na první pohled hodnoty některých řádků výsledku, můžeme je vyplnit hned do výsledku a v pomocných sloupcích je přeskočit. Důležitý je pouze sloupec s výsledkem a sloupce ABC, zbytek jsou mezivýpočty.
tj. vysvětlit, jak to vlastne udělat, případně tipy a triky.

**Comment by jaywor1** [comment]
> TODO:
> 
> > * [x]  U příkladu kde vytváříš zapojení, by bylo vhodné pod to zapojení poznamenat, že:
> >   Hradla OR na pravé straně můžou být v libovolném pořadí nebo nahrazeny 3-vstupovým OR, jelikož sčítání je asociativní a komutativní.
> 
> > * [x]  U tabulky pak: Vytváření tabulky si ulehčíme spočítáním sloupců pro námi zvolené podvýrazy, jejich hodnoty použijeme v dalších výpočtech, abychom se vyhnuli chybám při počítání komplikovaných výrazu z hlavy. Pokud víme na první pohled hodnoty některých řádků výsledku, můžeme je vyplnit hned do výsledku a v pomocných sloupcích je přeskočit. Důležitý je pouze sloupec s výsledkem a sloupce ABC, zbytek jsou mezivýpočty.
> >   tj. vysvětlit, jak to vlastne udělat, případně tipy a triky.

Done https://github.com/jaywor1/aps/pull/47
